CREATE TABLE practices
(
    id serial NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    course smallint NOT NULL,
    place VARCHAR(100) NOT NULL,
    position VARCHAR(100) NULL,
    page CHAR(1) NOT NULL,
    student_id          INT NOT NULL REFERENCES students (id)
);

insert into practices (id, name, course, place, position, page, student_id) values (1, 'Prodder', 10, '03550 Crest Line Lane', '0 Mockingbird Center', 1, 43);
insert into practices (id, name, course, place, position, page, student_id) values (2, 'Tres-Zap', 8, '1 Clarendon Circle', '3423 Browning Lane', 2, 50);
insert into practices (id, name, course, place, position, page, student_id) values (3, 'Mat Lam Tam', 5, '2240 Trailsway Court', '30030 Linden Lane', 2, 20);
insert into practices (id, name, course, place, position, page, student_id) values (4, 'Mat Lam Tam', 4, '54 Eastlawn Parkway', '9 Huxley Road', 1, 165);
insert into practices (id, name, course, place, position, page, student_id) values (5, 'Tresom', 8, '7 Sullivan Hill', '21233 Manufacturers Way', 1, 98);
insert into practices (id, name, course, place, position, page, student_id) values (6, 'Zoolab', 4, '1724 Transport Street', '8245 Melody Park', 1, 133);
insert into practices (id, name, course, place, position, page, student_id) values (7, 'Greenlam', 9, '1 Ramsey Junction', '6361 Boyd Hill', 2, 164);
insert into practices (id, name, course, place, position, page, student_id) values (8, 'Bamity', 4, '70 Prairie Rose Point', '93 Little Fleur Lane', 1, 81);
insert into practices (id, name, course, place, position, page, student_id) values (9, 'Bamity', 8, '639 Mesta Park', '8 Cascade Plaza', 2, 168);
insert into practices (id, name, course, place, position, page, student_id) values (10, 'Zaam-Dox', 9, '40 Golden Leaf Place', '291 Spenser Point', 2, 176);
insert into practices (id, name, course, place, position, page, student_id) values (11, 'Zontrax', 2, '9 Moose Avenue', '8 Burning Wood Trail', 1, 17);
insert into practices (id, name, course, place, position, page, student_id) values (12, 'It', 8, '846 Grayhawk Point', '607 Dryden Junction', 1, 181);
insert into practices (id, name, course, place, position, page, student_id) values (13, 'Konklab', 6, '2 La Follette Road', '557 Anderson Center', 1, 167);
insert into practices (id, name, course, place, position, page, student_id) values (14, 'Alpha', 1, '0985 Oak Way', '3 Cambridge Trail', 1, 36);
insert into practices (id, name, course, place, position, page, student_id) values (15, 'Stronghold', 6, '53 Pankratz Lane', '92143 Marcy Court', 2, 94);
insert into practices (id, name, course, place, position, page, student_id) values (16, 'Bigtax', 3, '08724 Norway Maple Plaza', '7476 Karstens Circle', 1, 64);
insert into practices (id, name, course, place, position, page, student_id) values (17, 'Andalax', 2, '0596 Luster Point', '26508 Sheridan Lane', 1, 136);
insert into practices (id, name, course, place, position, page, student_id) values (18, 'Ventosanzap', 3, '9475 Sycamore Street', '8041 Fuller Drive', 1, 125);
insert into practices (id, name, course, place, position, page, student_id) values (19, 'Treeflex', 3, '8 Main Terrace', '29086 Commercial Circle', 2, 167);
insert into practices (id, name, course, place, position, page, student_id) values (20, 'Tres-Zap', 4, '97 Linden Road', '817 Forster Center', 2, 150);
insert into practices (id, name, course, place, position, page, student_id) values (21, 'Bytecard', 2, '04 Prairieview Place', '03 Dennis Crossing', 1, 121);
insert into practices (id, name, course, place, position, page, student_id) values (22, 'Zontrax', 7, '141 Drewry Road', '883 Dahle Center', 2, 44);
insert into practices (id, name, course, place, position, page, student_id) values (23, 'Job', 2, '22 Graceland Crossing', '3322 Beilfuss Terrace', 2, 192);
insert into practices (id, name, course, place, position, page, student_id) values (24, 'Hatity', 8, '1877 Farwell Lane', '56536 Golf View Drive', 1, 112);
insert into practices (id, name, course, place, position, page, student_id) values (25, 'Prodder', 4, '6887 Golden Leaf Hill', '89 Lerdahl Junction', 1, 160);
insert into practices (id, name, course, place, position, page, student_id) values (26, 'Regrant', 7, '14794 North Trail', '6359 Montana Way', 1, 115);
insert into practices (id, name, course, place, position, page, student_id) values (27, 'Ronstring', 3, '6933 Cottonwood Lane', '1 Lakewood Junction', 1, 96);
insert into practices (id, name, course, place, position, page, student_id) values (28, 'Fixflex', 7, '5983 Esch Trail', '5364 Kings Court', 2, 118);
insert into practices (id, name, course, place, position, page, student_id) values (29, 'Zaam-Dox', 1, '1288 Old Gate Parkway', '05 Bayside Lane', 2, 65);
insert into practices (id, name, course, place, position, page, student_id) values (30, 'Stringtough', 6, '546 Del Sol Hill', '21599 Dorton Alley', 1, 185);
insert into practices (id, name, course, place, position, page, student_id) values (31, 'Pannier', 4, '34 Macpherson Court', '7021 Commercial Parkway', 1, 153);
insert into practices (id, name, course, place, position, page, student_id) values (32, 'Lotstring', 5, '29929 Oriole Center', '8421 Randy Terrace', 2, 62);
insert into practices (id, name, course, place, position, page, student_id) values (33, 'Tresom', 3, '065 Oneill Court', '6 Oxford Center', 2, 29);
insert into practices (id, name, course, place, position, page, student_id) values (34, 'Alpha', 5, '7 Florence Parkway', '94 Delladonna Drive', 2, 75);
insert into practices (id, name, course, place, position, page, student_id) values (35, 'Veribet', 1, '5 Green Drive', '1 Rigney Trail', 2, 4);
insert into practices (id, name, course, place, position, page, student_id) values (36, 'Sonsing', 8, '04 Lakeland Park', '89 Eggendart Court', 1, 10);
insert into practices (id, name, course, place, position, page, student_id) values (37, 'Flexidy', 1, '839 Muir Junction', '1 Sommers Avenue', 1, 32);
insert into practices (id, name, course, place, position, page, student_id) values (38, 'Sonair', 10, '84 Summit Place', '11 Dorton Alley', 1, 157);
insert into practices (id, name, course, place, position, page, student_id) values (39, 'Job', 2, '8 Sherman Avenue', '39 Colorado Park', 2, 2);
insert into practices (id, name, course, place, position, page, student_id) values (40, 'Biodex', 3, '81340 Vera Crossing', '70422 Sherman Center', 2, 159);
insert into practices (id, name, course, place, position, page, student_id) values (41, 'Zathin', 10, '06 Northwestern Point', '5 Hansons Alley', 1, 146);
insert into practices (id, name, course, place, position, page, student_id) values (42, 'Fix San', 6, '92211 Myrtle Plaza', '703 Brentwood Place', 1, 125);
insert into practices (id, name, course, place, position, page, student_id) values (43, 'Ventosanzap', 5, '03 Dawn Point', '5 Bluestem Street', 1, 172);
insert into practices (id, name, course, place, position, page, student_id) values (44, 'Prodder', 6, '60 Lake View Trail', '71922 Del Mar Circle', 2, 11);
insert into practices (id, name, course, place, position, page, student_id) values (45, 'Viva', 3, '149 Artisan Road', '09 Anhalt Street', 2, 162);
insert into practices (id, name, course, place, position, page, student_id) values (46, 'Matsoft', 6, '42 Jackson Terrace', '051 New Castle Terrace', 1, 114);
insert into practices (id, name, course, place, position, page, student_id) values (47, 'Stronghold', 6, '6411 Bayside Place', '681 Duke Street', 2, 86);
insert into practices (id, name, course, place, position, page, student_id) values (48, 'Konklab', 8, '733 Twin Pines Parkway', '87630 Stephen Road', 1, 180);
insert into practices (id, name, course, place, position, page, student_id) values (49, 'Biodex', 3, '0931 Weeping Birch Parkway', '7458 Anhalt Terrace', 1, 2);
insert into practices (id, name, course, place, position, page, student_id) values (50, 'Prodder', 3, '24408 Evergreen Circle', '5 Packers Hill', 2, 129);
insert into practices (id, name, course, place, position, page, student_id) values (51, 'Voyatouch', 5, '80044 Larry Road', '901 Dorton Street', 2, 166);
insert into practices (id, name, course, place, position, page, student_id) values (52, 'Stronghold', 6, '37 Graedel Road', '3 Merchant Park', 1, 30);
insert into practices (id, name, course, place, position, page, student_id) values (53, 'Tres-Zap', 3, '09 Crest Line Center', '44 Colorado Trail', 2, 76);
insert into practices (id, name, course, place, position, page, student_id) values (54, 'Lotlux', 9, '16619 Nobel Center', '365 Graedel Plaza', 2, 23);
insert into practices (id, name, course, place, position, page, student_id) values (55, 'Alpha', 10, '256 Park Meadow Drive', '673 Jana Court', 2, 28);
insert into practices (id, name, course, place, position, page, student_id) values (56, 'Y-find', 1, '738 Evergreen Center', '81564 Spenser Crossing', 1, 86);
insert into practices (id, name, course, place, position, page, student_id) values (57, 'Bitwolf', 10, '49 Oak Valley Center', '5 Green Ridge Pass', 2, 150);
insert into practices (id, name, course, place, position, page, student_id) values (58, 'Tempsoft', 4, '9 Kim Avenue', '9862 Hallows Park', 2, 153);
insert into practices (id, name, course, place, position, page, student_id) values (59, 'Y-Solowarm', 7, '39 Bluejay Terrace', '92 Saint Paul Court', 2, 178);
insert into practices (id, name, course, place, position, page, student_id) values (60, 'Tres-Zap', 10, '64 Mayfield Court', '955 Saint Paul Junction', 2, 34);
insert into practices (id, name, course, place, position, page, student_id) values (61, 'Cookley', 7, '009 Eastwood Terrace', '5 Sachs Lane', 1, 69);
insert into practices (id, name, course, place, position, page, student_id) values (62, 'Zoolab', 10, '9584 Butterfield Court', '5 Sachtjen Terrace', 1, 8);
insert into practices (id, name, course, place, position, page, student_id) values (63, 'It', 10, '34 Banding Place', '191 Sachtjen Road', 1, 93);
insert into practices (id, name, course, place, position, page, student_id) values (64, 'Voltsillam', 8, '842 Lukken Street', '9304 Del Mar Crossing', 2, 150);
insert into practices (id, name, course, place, position, page, student_id) values (65, 'Trippledex', 3, '96874 Washington Pass', '95532 2nd Crossing', 1, 28);
insert into practices (id, name, course, place, position, page, student_id) values (66, 'Holdlamis', 10, '2970 Northport Road', '69667 Mariners Cove Road', 2, 197);
insert into practices (id, name, course, place, position, page, student_id) values (67, 'Rank', 8, '268 Di Loreto Parkway', '82415 Lien Parkway', 2, 114);
insert into practices (id, name, course, place, position, page, student_id) values (68, 'Latlux', 7, '54121 Cordelia Hill', '10005 Waywood Place', 1, 32);
insert into practices (id, name, course, place, position, page, student_id) values (69, 'Subin', 7, '600 Spaight Alley', '7 Duke Avenue', 2, 184);
insert into practices (id, name, course, place, position, page, student_id) values (70, 'Voltsillam', 8, '64 Mallory Street', '066 Ruskin Avenue', 1, 29);
insert into practices (id, name, course, place, position, page, student_id) values (71, 'Flexidy', 10, '74433 Doe Crossing Street', '9 Corben Terrace', 1, 61);
insert into practices (id, name, course, place, position, page, student_id) values (72, 'Home Ing', 5, '06633 Linden Alley', '21 Westport Pass', 1, 24);
insert into practices (id, name, course, place, position, page, student_id) values (73, 'Trippledex', 9, '56185 Arizona Avenue', '7 Merchant Alley', 2, 189);
insert into practices (id, name, course, place, position, page, student_id) values (74, 'Bitchip', 6, '36 Eastlawn Street', '76 Village Green Drive', 2, 108);
insert into practices (id, name, course, place, position, page, student_id) values (75, 'Rank', 4, '52609 Pearson Crossing', '1 Charing Cross Park', 2, 186);
insert into practices (id, name, course, place, position, page, student_id) values (76, 'Y-find', 2, '30757 Lien Crossing', '61 Sherman Street', 1, 20);
insert into practices (id, name, course, place, position, page, student_id) values (77, 'Flowdesk', 10, '25 Buhler Point', '989 Graceland Plaza', 2, 24);
insert into practices (id, name, course, place, position, page, student_id) values (78, 'Sonair', 8, '56555 Bowman Way', '1 Tomscot Plaza', 2, 21);
insert into practices (id, name, course, place, position, page, student_id) values (79, 'Otcom', 2, '35471 Brown Road', '7115 Truax Parkway', 2, 33);
insert into practices (id, name, course, place, position, page, student_id) values (80, 'Otcom', 1, '178 Gina Lane', '85855 Briar Crest Avenue', 2, 97);
insert into practices (id, name, course, place, position, page, student_id) values (81, 'Gembucket', 4, '30015 Division Crossing', '3417 Melby Point', 1, 147);
insert into practices (id, name, course, place, position, page, student_id) values (82, 'Voyatouch', 4, '46 Schurz Point', '57 Judy Pass', 2, 81);
insert into practices (id, name, course, place, position, page, student_id) values (83, 'Home Ing', 6, '62297 Hauk Trail', '0929 Caliangt Park', 2, 200);
insert into practices (id, name, course, place, position, page, student_id) values (84, 'Kanlam', 2, '14 Garrison Circle', '97421 Norway Maple Alley', 2, 126);
insert into practices (id, name, course, place, position, page, student_id) values (85, 'Rank', 5, '220 Rutledge Way', '0262 Doe Crossing Terrace', 1, 134);
insert into practices (id, name, course, place, position, page, student_id) values (86, 'Bamity', 6, '76 Holmberg Circle', '35 Golf View Point', 2, 105);
insert into practices (id, name, course, place, position, page, student_id) values (87, 'Biodex', 2, '0085 Heffernan Park', '9 Red Cloud Trail', 2, 98);
insert into practices (id, name, course, place, position, page, student_id) values (88, 'Regrant', 8, '92123 Moland Place', '84053 Brentwood Drive', 2, 77);
insert into practices (id, name, course, place, position, page, student_id) values (89, 'Y-find', 9, '4 Blue Bill Park Terrace', '28896 Carpenter Plaza', 1, 42);
insert into practices (id, name, course, place, position, page, student_id) values (90, 'Tresom', 6, '0357 Namekagon Point', '8 Rockefeller Drive', 1, 114);
insert into practices (id, name, course, place, position, page, student_id) values (91, 'Matsoft', 6, '156 Hovde Place', '8354 4th Lane', 2, 116);
insert into practices (id, name, course, place, position, page, student_id) values (92, 'Transcof', 9, '8 Stephen Plaza', '5 New Castle Circle', 1, 160);
insert into practices (id, name, course, place, position, page, student_id) values (93, 'Bytecard', 10, '36472 Morning Junction', '69295 Monica Center', 2, 170);
insert into practices (id, name, course, place, position, page, student_id) values (94, 'Sub-Ex', 5, '47330 Dorton Street', '0727 Russell Drive', 1, 177);
insert into practices (id, name, course, place, position, page, student_id) values (95, 'Wrapsafe', 10, '4035 Roth Terrace', '6685 Sauthoff Junction', 1, 43);
insert into practices (id, name, course, place, position, page, student_id) values (96, 'Quo Lux', 3, '406 Crowley Parkway', '641 Sunbrook Parkway', 1, 174);
insert into practices (id, name, course, place, position, page, student_id) values (97, 'Rank', 10, '3 High Crossing Avenue', '8 Talmadge Hill', 1, 188);
insert into practices (id, name, course, place, position, page, student_id) values (98, 'Trippledex', 9, '8714 Gale Place', '443 Hoard Street', 2, 142);
insert into practices (id, name, course, place, position, page, student_id) values (99, 'Konklux', 3, '4 Quincy Trail', '50 Mifflin Park', 2, 103);
insert into practices (id, name, course, place, position, page, student_id) values (100, 'Quo Lux', 8, '78 Browning Pass', '90737 Briar Crest Center', 1, 136);
insert into practices (id, name, course, place, position, page, student_id) values (101, 'Lotstring', 9, '7 Granby Crossing', '8039 Forest Hill', 2, 81);
insert into practices (id, name, course, place, position, page, student_id) values (102, 'Veribet', 10, '5898 Raven Way', '55781 Melrose Junction', 2, 14);
insert into practices (id, name, course, place, position, page, student_id) values (103, 'Fixflex', 3, '2564 Scofield Street', '201 Morning Pass', 1, 89);
insert into practices (id, name, course, place, position, page, student_id) values (104, 'Namfix', 10, '78848 Fordem Terrace', '610 Laurel Pass', 2, 74);
insert into practices (id, name, course, place, position, page, student_id) values (105, 'Sonair', 5, '576 Moulton Center', '4385 Moland Court', 2, 22);
insert into practices (id, name, course, place, position, page, student_id) values (106, 'Mat Lam Tam', 3, '6403 Warrior Center', '2 Carey Court', 1, 77);
insert into practices (id, name, course, place, position, page, student_id) values (107, 'Pannier', 4, '6298 Lake View Drive', '042 Transport Terrace', 1, 25);
insert into practices (id, name, course, place, position, page, student_id) values (108, 'Sub-Ex', 4, '02 Veith Avenue', '70 Dexter Place', 2, 156);
insert into practices (id, name, course, place, position, page, student_id) values (109, 'Redhold', 7, '7451 Bartillon Crossing', '4972 Spenser Trail', 2, 156);
insert into practices (id, name, course, place, position, page, student_id) values (110, 'Tampflex', 7, '6 Dawn Street', '6 Mitchell Drive', 2, 138);
insert into practices (id, name, course, place, position, page, student_id) values (111, 'Tin', 3, '314 Crescent Oaks Avenue', '5 Scofield Way', 1, 105);
insert into practices (id, name, course, place, position, page, student_id) values (112, 'Sonsing', 3, '2120 Menomonie Drive', '728 Emmet Circle', 1, 106);
insert into practices (id, name, course, place, position, page, student_id) values (113, 'Ventosanzap', 4, '5925 Dixon Point', '020 4th Lane', 1, 156);
insert into practices (id, name, course, place, position, page, student_id) values (114, 'Zaam-Dox', 7, '318 Randy Road', '2 Roxbury Pass', 1, 49);
insert into practices (id, name, course, place, position, page, student_id) values (115, 'Viva', 7, '4 Delaware Junction', '0922 Transport Street', 1, 191);
insert into practices (id, name, course, place, position, page, student_id) values (116, 'Home Ing', 1, '4 Delladonna Center', '20 Westend Circle', 1, 50);
insert into practices (id, name, course, place, position, page, student_id) values (117, 'Temp', 6, '436 Nova Parkway', '55 Spenser Avenue', 2, 195);
insert into practices (id, name, course, place, position, page, student_id) values (118, 'Andalax', 3, '3602 Summerview Plaza', '5 Anniversary Pass', 2, 186);
insert into practices (id, name, course, place, position, page, student_id) values (119, 'Quo Lux', 9, '00188 Judy Center', '302 Longview Alley', 1, 69);
insert into practices (id, name, course, place, position, page, student_id) values (120, 'Latlux', 3, '1 Golden Leaf Crossing', '5490 Lakeland Alley', 1, 173);
insert into practices (id, name, course, place, position, page, student_id) values (121, 'Y-find', 2, '22958 Gulseth Center', '5638 Tony Street', 2, 191);
insert into practices (id, name, course, place, position, page, student_id) values (122, 'Temp', 8, '61 Oak Valley Court', '89 Everett Junction', 1, 112);
insert into practices (id, name, course, place, position, page, student_id) values (123, 'Temp', 3, '9 Fallview Park', '4 Hoepker Avenue', 2, 170);
insert into practices (id, name, course, place, position, page, student_id) values (124, 'Kanlam', 1, '24691 Forest Street', '50 Daystar Parkway', 2, 83);
insert into practices (id, name, course, place, position, page, student_id) values (125, 'Tin', 1, '4603 Rusk Place', '28749 Forest Dale Lane', 2, 199);
insert into practices (id, name, course, place, position, page, student_id) values (126, 'Toughjoyfax', 2, '596 Park Meadow Place', '2803 Golden Leaf Crossing', 2, 59);
insert into practices (id, name, course, place, position, page, student_id) values (127, 'Bitchip', 2, '272 Ronald Regan Trail', '0716 Hovde Point', 1, 84);
insert into practices (id, name, course, place, position, page, student_id) values (128, 'Namfix', 5, '72518 Mandrake Alley', '6390 Sheridan Park', 1, 160);
insert into practices (id, name, course, place, position, page, student_id) values (129, 'Wrapsafe', 8, '84 High Crossing Plaza', '048 Sommers Trail', 1, 166);
insert into practices (id, name, course, place, position, page, student_id) values (130, 'Lotstring', 7, '6 Bellgrove Way', '30538 8th Drive', 1, 150);
insert into practices (id, name, course, place, position, page, student_id) values (131, 'Flowdesk', 6, '375 Schmedeman Terrace', '6988 Pond Way', 1, 25);
insert into practices (id, name, course, place, position, page, student_id) values (132, 'Zamit', 9, '59378 Sutteridge Pass', '0839 Pankratz Junction', 2, 167);
insert into practices (id, name, course, place, position, page, student_id) values (133, 'Zoolab', 8, '0 Laurel Lane', '994 Burrows Avenue', 2, 11);
insert into practices (id, name, course, place, position, page, student_id) values (134, 'Y-Solowarm', 9, '7705 Bartelt Alley', '0110 Golf Street', 2, 180);
insert into practices (id, name, course, place, position, page, student_id) values (135, 'Flowdesk', 2, '2100 Raven Plaza', '018 Karstens Plaza', 2, 37);
insert into practices (id, name, course, place, position, page, student_id) values (136, 'Y-Solowarm', 9, '285 Shasta Street', '2772 Rowland Road', 2, 4);
insert into practices (id, name, course, place, position, page, student_id) values (137, 'Opela', 6, '059 Anzinger Junction', '725 Debs Circle', 2, 5);
insert into practices (id, name, course, place, position, page, student_id) values (138, 'Bamity', 5, '35893 Ruskin Hill', '4 Mallard Pass', 2, 169);
insert into practices (id, name, course, place, position, page, student_id) values (139, 'Zamit', 8, '012 Jay Plaza', '8 Manitowish Avenue', 2, 16);
insert into practices (id, name, course, place, position, page, student_id) values (140, 'Stim', 7, '7966 Redwing Court', '8 Chive Place', 2, 154);
insert into practices (id, name, course, place, position, page, student_id) values (141, 'Sonsing', 3, '73770 Lunder Lane', '223 Prentice Hill', 2, 131);
insert into practices (id, name, course, place, position, page, student_id) values (142, 'Latlux', 2, '20791 Anderson Point', '65428 Kings Avenue', 1, 69);
insert into practices (id, name, course, place, position, page, student_id) values (143, 'Temp', 7, '61 Pankratz Alley', '44 Blackbird Street', 2, 47);
insert into practices (id, name, course, place, position, page, student_id) values (144, 'Rank', 9, '0 Merchant Junction', '2 Messerschmidt Plaza', 1, 27);
insert into practices (id, name, course, place, position, page, student_id) values (145, 'Biodex', 10, '0288 Aberg Parkway', '005 Buena Vista Crossing', 2, 151);
insert into practices (id, name, course, place, position, page, student_id) values (146, 'Overhold', 4, '2855 Ridgeview Point', '6615 Toban Parkway', 1, 177);
insert into practices (id, name, course, place, position, page, student_id) values (147, 'Otcom', 8, '7253 6th Pass', '8064 Mariners Cove Circle', 1, 182);
insert into practices (id, name, course, place, position, page, student_id) values (148, 'Konklab', 1, '91 Judy Lane', '45 Annamark Junction', 2, 177);
insert into practices (id, name, course, place, position, page, student_id) values (149, 'Biodex', 2, '50 Holmberg Parkway', '451 Sutteridge Parkway', 2, 74);
insert into practices (id, name, course, place, position, page, student_id) values (150, 'Ventosanzap', 7, '84 Valley Edge Alley', '8816 Susan Terrace', 1, 90);
insert into practices (id, name, course, place, position, page, student_id) values (151, 'Wrapsafe', 3, '423 Blackbird Pass', '29612 Hallows Road', 2, 4);
insert into practices (id, name, course, place, position, page, student_id) values (152, 'Hatity', 8, '99 Sage Circle', '47 Packers Road', 2, 174);
insert into practices (id, name, course, place, position, page, student_id) values (153, 'Solarbreeze', 7, '932 Center Parkway', '3 Esch Court', 2, 181);
insert into practices (id, name, course, place, position, page, student_id) values (154, 'Sonsing', 5, '486 Stuart Avenue', '69554 New Castle Street', 1, 39);
insert into practices (id, name, course, place, position, page, student_id) values (155, 'Bamity', 3, '823 Bartillon Trail', '3 Prairieview Pass', 2, 164);
insert into practices (id, name, course, place, position, page, student_id) values (156, 'Overhold', 1, '9862 Forster Plaza', '889 Dottie Junction', 2, 172);
insert into practices (id, name, course, place, position, page, student_id) values (157, 'Cardify', 9, '99011 Hanson Center', '77 Moulton Junction', 1, 4);
insert into practices (id, name, course, place, position, page, student_id) values (158, 'Tampflex', 7, '167 Mandrake Center', '00195 Jenna Trail', 1, 84);
insert into practices (id, name, course, place, position, page, student_id) values (159, 'Duobam', 6, '8 4th Park', '51 Cambridge Terrace', 1, 174);
insert into practices (id, name, course, place, position, page, student_id) values (160, 'Voltsillam', 10, '63345 Arkansas Terrace', '45129 High Crossing Circle', 1, 178);
insert into practices (id, name, course, place, position, page, student_id) values (161, 'Zathin', 10, '815 Old Shore Hill', '1985 Rusk Crossing', 1, 54);
insert into practices (id, name, course, place, position, page, student_id) values (162, 'Treeflex', 6, '9608 Aberg Place', '064 Messerschmidt Pass', 1, 97);
insert into practices (id, name, course, place, position, page, student_id) values (163, 'Duobam', 4, '65769 Pepper Wood Avenue', '088 Lien Circle', 2, 104);
insert into practices (id, name, course, place, position, page, student_id) values (164, 'Namfix', 8, '18803 Bashford Road', '11 Southridge Avenue', 1, 149);
insert into practices (id, name, course, place, position, page, student_id) values (165, 'Flexidy', 1, '2 Sheridan Point', '96014 Kipling Parkway', 1, 74);
insert into practices (id, name, course, place, position, page, student_id) values (166, 'Prodder', 3, '47 Vidon Terrace', '03308 Onsgard Junction', 2, 183);
insert into practices (id, name, course, place, position, page, student_id) values (167, 'Rank', 3, '94918 Buell Center', '731 Welch Point', 1, 11);
insert into practices (id, name, course, place, position, page, student_id) values (168, 'Alphazap', 2, '914 Erie Parkway', '49 Center Lane', 2, 84);
insert into practices (id, name, course, place, position, page, student_id) values (169, 'Keylex', 9, '89 Glacier Hill Pass', '87 Londonderry Trail', 1, 9);
insert into practices (id, name, course, place, position, page, student_id) values (170, 'Job', 2, '44 Thompson Drive', '8140 Ohio Alley', 2, 176);
insert into practices (id, name, course, place, position, page, student_id) values (171, 'Gembucket', 9, '38534 Pankratz Road', '5856 Lyons Parkway', 1, 116);
insert into practices (id, name, course, place, position, page, student_id) values (172, 'Matsoft', 1, '16 Evergreen Terrace', '47539 Magdeline Lane', 2, 93);
insert into practices (id, name, course, place, position, page, student_id) values (173, 'It', 1, '12 Everett Junction', '13 Emmet Terrace', 1, 200);
insert into practices (id, name, course, place, position, page, student_id) values (174, 'Sonsing', 2, '52 Anthes Pass', '13141 International Pass', 2, 91);
insert into practices (id, name, course, place, position, page, student_id) values (175, 'Home Ing', 2, '7099 Delladonna Road', '951 Maryland Avenue', 2, 38);
insert into practices (id, name, course, place, position, page, student_id) values (176, 'Vagram', 5, '9575 Corscot Crossing', '10 Clarendon Point', 1, 60);
insert into practices (id, name, course, place, position, page, student_id) values (177, 'Ronstring', 6, '2047 Mandrake Court', '13243 Basil Drive', 2, 197);
insert into practices (id, name, course, place, position, page, student_id) values (178, 'Matsoft', 4, '1466 Dixon Circle', '9 Bluestem Alley', 2, 102);
insert into practices (id, name, course, place, position, page, student_id) values (179, 'Greenlam', 2, '4113 Northridge Pass', '406 Ridgeway Plaza', 1, 182);
insert into practices (id, name, course, place, position, page, student_id) values (180, 'Hatity', 9, '162 Arizona Drive', '8 Dakota Avenue', 2, 113);
insert into practices (id, name, course, place, position, page, student_id) values (181, 'Redhold', 4, '9185 Butternut Park', '0 Ilene Street', 1, 174);
insert into practices (id, name, course, place, position, page, student_id) values (182, 'Fixflex', 3, '268 Dennis Street', '762 Helena Junction', 2, 86);
insert into practices (id, name, course, place, position, page, student_id) values (183, 'Subin', 3, '09 Northland Court', '245 Twin Pines Avenue', 1, 151);
insert into practices (id, name, course, place, position, page, student_id) values (184, 'Biodex', 3, '32194 Fieldstone Parkway', '68 Logan Crossing', 1, 173);
insert into practices (id, name, course, place, position, page, student_id) values (185, 'Alphazap', 10, '0 Eliot Pass', '99997 Sutherland Avenue', 2, 78);
insert into practices (id, name, course, place, position, page, student_id) values (186, 'Voyatouch', 9, '32 Merry Alley', '05204 Banding Hill', 1, 179);
insert into practices (id, name, course, place, position, page, student_id) values (187, 'Sub-Ex', 8, '96371 Mariners Cove Center', '0 Hagan Street', 1, 162);
insert into practices (id, name, course, place, position, page, student_id) values (188, 'Flowdesk', 3, '8366 Hermina Terrace', '90 International Alley', 1, 67);
insert into practices (id, name, course, place, position, page, student_id) values (189, 'Gembucket', 9, '14 Toban Road', '43517 Granby Road', 1, 128);
insert into practices (id, name, course, place, position, page, student_id) values (190, 'Rank', 4, '109 Bashford Park', '959 Caliangt Trail', 1, 56);
insert into practices (id, name, course, place, position, page, student_id) values (191, 'Voltsillam', 2, '68 Rusk Plaza', '00166 Spohn Avenue', 2, 87);
insert into practices (id, name, course, place, position, page, student_id) values (192, 'Holdlamis', 3, '3455 Spenser Plaza', '6564 American Pass', 1, 84);
insert into practices (id, name, course, place, position, page, student_id) values (193, 'Home Ing', 9, '9 Main Court', '61647 Almo Lane', 2, 99);
insert into practices (id, name, course, place, position, page, student_id) values (194, 'Voyatouch', 2, '23 Gina Pass', '334 Utah Circle', 1, 24);
insert into practices (id, name, course, place, position, page, student_id) values (195, 'Konklux', 6, '90139 Lakeland Pass', '8 Norway Maple Junction', 2, 76);
insert into practices (id, name, course, place, position, page, student_id) values (196, 'Bigtax', 3, '26 Stephen Avenue', '3893 Columbus Pass', 1, 122);
insert into practices (id, name, course, place, position, page, student_id) values (197, 'Greenlam', 5, '1920 Stuart Point', '13 Luster Drive', 2, 171);
insert into practices (id, name, course, place, position, page, student_id) values (198, 'Otcom', 10, '708 Homewood Center', '4125 Fulton Point', 1, 148);
insert into practices (id, name, course, place, position, page, student_id) values (199, 'Job', 3, '6796 Crescent Oaks Point', '456 Golf Course Park', 2, 134);
insert into practices (id, name, course, place, position, page, student_id) values (200, 'Latlux', 10, '5048 Fulton Avenue', '08454 Northport Hill', 2, 24);
