--  id                   | bigint                |           | not null | nextval('teachers_id_seq'::regclass)
--  first_name           | character varying(50) |           | not null |
--  last_name            | character varying(50) |           | not null |
--  futher_name          | character varying(50) |           | not null |
--  department           | character varying(50) |           | not null |
--  salary               | integer               |           | not null |
--  qualification_level  | character varying(50) |           | not null |
--  contract_termination | date                  |           | not null |

CREATE TABLE teachers
(
    id serial NOT NULL PRIMARY KEY,
    first_name            character varying(50)             not null,
    last_name             character varying(50)             not null,
    futher_name           character varying(50)             not null,
    department            character varying(50)             null,
    salary                integer                           null,
    qualification_level   character varying(50)             null,
    contract_termination  date                              not null
);


-- UPDATE teachers SET qualification_level = 'teacher' WHERE teachers.id = 1;

-- --DELETE FROM teachers WHERE id <> 0;
-- INSERT INTO teachers (first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES ('Boris', 'Borisenko', 'Borisovich', 'CT', 10000, 'professor', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (2, 'Валерій', 'Сімоненко', 'Павлович', 'ОТ', 10000, 'професор', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (3, 'Олександра', 'Бойко', 'Володимирівна', 'АУТС', 10000, 'викладач', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (4, 'Володимир', 'Шимкович', 'Миколайович', 'ОТ', 10000, 'викладач', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (5, 'Ксенія', 'Ульяницька', 'Олександрівна', 'АУТС', 10000, 'викладач', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (6, 'Роман', 'Мазур', '', 'АУТС', 10000, 'викладач', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (7, 'Тимур', 'Шемсединов', 'Гафарович', 'ОТ', 10000, 'асистент', '2021-06-21');
-- INSERT INTO teachers (id, first_name, last_name, futher_name, department, salary, qualification_level, contract_termination) VALUES (8, '', '', '', '', 10000, '', '2021-06-21');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (1, 'Esdras', 'Kerk', 'Research and Development', 359530, 'Mr', '9/13/2022', 'Zannutti');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (2, 'Claiborne', 'Clement', 'Sales', 943321, 'Honorable', '10/8/2021', 'Aynold');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (3, 'Nolana', 'De witt', 'Legal', 27529, 'Honorable', '11/18/2021', 'Rogliero');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (4, 'Jesselyn', 'Iain', 'Support', 388865, 'Rev', '4/11/2020', 'Remon');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (5, 'Nate', 'Marc', 'Business Development', 330371, 'Mrs', '10/21/2020', 'Densie');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (6, 'Torrin', 'Kane', 'Business Development', 161296, 'Ms', '9/30/2020', 'Shorto');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (7, 'Winny', 'Prince', 'Legal', 525364, 'Ms', '9/24/2020', 'Keast');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (8, 'Alberik', 'Sonnie', 'Engineering', 953915, 'Mrs', '4/6/2021', 'Fedder');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (9, 'Sibley', 'Galvin', 'Research and Development', 769037, 'Ms', '10/10/2021', 'Eason');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (10, 'Emelyne', 'Izak', 'Business Development', 638656, 'Honorable', '11/2/2022', 'Birdseye');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (11, 'Eugen', 'Andrej', 'Legal', 882023, 'Mrs', '1/25/2020', 'Phifer');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (12, 'Jayme', 'Andre', 'Research and Development', 57400, 'Ms', '1/2/2022', 'Farris');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (13, 'Tanny', 'Merv', 'Support', 725288, 'Mrs', '7/27/2020', 'Houltham');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (14, 'Mose', 'Waiter', 'Support', 793006, 'Honorable', '11/16/2021', 'Logesdale');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (15, 'Berton', 'Barnebas', 'Sales', 938947, 'Rev', '9/2/2022', 'Hawick');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (16, 'Hakim', 'Michel', 'Services', 872617, 'Mr', '10/21/2021', 'Teese');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (17, 'Jamesy', 'Mata', 'Engineering', 506352, 'Dr', '9/18/2021', 'Oels');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (18, 'Alessandra', 'Stanford', 'Support', 33110, 'Dr', '7/8/2022', 'Richmond');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (19, 'Bethanne', 'Harper', 'Accounting', 717676, 'Honorable', '4/25/2021', 'Jolly');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (20, 'Jenn', 'Norrie', 'Training', 136601, 'Mrs', '10/26/2020', 'Heartfield');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (21, 'Brigida', 'Artur', 'Legal', 698202, 'Ms', '2/14/2021', 'Feares');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (22, 'Jazmin', 'Barnabe', 'Engineering', 746995, 'Mr', '1/19/2022', 'Parton');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (23, 'Viole', 'Brocky', 'Legal', 532527, 'Mrs', '7/17/2020', 'Trubshaw');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (24, 'Jonis', 'Willem', 'Product Management', 60710, 'Ms', '12/14/2021', 'Birnie');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (25, 'Randie', 'Rogers', 'Sales', 105750, 'Honorable', '11/7/2020', 'Peter');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (26, 'Tomas', 'Barnebas', 'Research and Development', 22754, 'Dr', '10/30/2020', 'Surby');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (27, 'Delaney', 'Raffarty', 'Services', 476088, 'Honorable', '5/13/2020', 'Narey');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (28, 'Brunhilda', 'Cristian', 'Training', 950883, 'Mrs', '9/11/2021', 'Fowle');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (29, 'Antony', 'Iggie', 'Training', 739952, 'Mrs', '9/16/2020', 'Tixier');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (30, 'Kirby', 'Wade', 'Engineering', 112827, 'Mrs', '2/17/2020', 'Nesterov');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (31, 'Debby', 'Gayle', 'Research and Development', 359305, 'Mr', '2/16/2022', 'Ridgley');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (32, 'Xenia', 'Jabez', 'Research and Development', 634491, 'Honorable', '11/9/2021', 'Lowndsbrough');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (33, 'Wilmer', 'Griffin', 'Research and Development', 839342, 'Honorable', '1/21/2022', 'Cantero');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (34, 'Englebert', 'Thoma', 'Support', 444762, 'Ms', '11/29/2020', 'Kyndred');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (35, 'Vanessa', 'Rabi', 'Engineering', 807304, 'Mrs', '6/20/2020', 'Frantzen');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (36, 'Man', 'Thurston', 'Training', 690740, 'Mr', '7/30/2020', 'Gallop');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (37, 'Gwyn', 'Towney', 'Product Management', 438292, 'Dr', '10/15/2022', 'Jiggle');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (38, 'Jessamine', 'Marcus', 'Support', 271387, 'Dr', '6/17/2020', 'Tante');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (39, 'Conway', 'Timothee', 'Sales', 462716, 'Ms', '8/7/2022', 'Bernhardt');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (40, 'Dino', 'Ermanno', 'Sales', 3091, 'Honorable', '12/6/2020', 'Brundale');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (41, 'Winne', 'Harbert', 'Human Resources', 272261, 'Rev', '5/7/2022', 'Galbreath');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (42, 'Amabel', 'Giavani', 'Business Development', 561695, 'Mrs', '7/11/2021', 'Streatfeild');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (43, 'Lesli', 'Dorie', 'Legal', 905667, 'Rev', '5/28/2020', 'Huckleby');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (44, 'Boniface', 'Bren', 'Business Development', 445987, 'Honorable', '12/13/2019', 'Hargate');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (45, 'Zaria', 'Massimiliano', 'Business Development', 556618, 'Ms', '6/13/2022', 'Thomsson');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (46, 'Rosabella', 'Joel', 'Legal', 101818, 'Dr', '1/8/2022', 'Lehr');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (47, 'Diann', 'Louis', 'Training', 918033, 'Mr', '10/30/2020', 'Blenkinship');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (48, 'Amberly', 'Leonid', 'Research and Development', 76089, 'Mr', '8/30/2021', 'McCalister');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (49, 'Tiffie', 'Glenden', 'Product Management', 765811, 'Ms', '11/17/2022', 'Scrane');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (50, 'Xenos', 'Brandyn', 'Services', 494912, 'Dr', '3/10/2022', 'Zuker');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (51, 'Hertha', 'Grantham', 'Accounting', 946174, 'Honorable', '3/24/2022', 'Hrihorovich');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (52, 'Wren', 'Nathan', 'Services', 265666, 'Rev', '12/21/2019', 'Bemlott');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (53, 'Elsy', 'Brennan', 'Sales', 73381, 'Mrs', '11/19/2019', 'Douche');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (54, 'Yurik', 'Michael', 'Legal', 795659, 'Mrs', '4/6/2021', 'Desforges');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (55, 'Wernher', 'Jeffrey', 'Business Development', 854897, 'Mrs', '7/6/2021', 'Trustie');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (56, 'Virginie', 'Vladamir', 'Business Development', 562769, 'Dr', '12/29/2021', 'Thys');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (57, 'Corbet', 'Clayton', 'Training', 996708, 'Mr', '3/10/2021', 'Galbreath');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (58, 'Florri', 'Danny', 'Support', 977959, 'Honorable', '7/20/2022', 'Meffin');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (59, 'Blondy', 'Tobin', 'Marketing', 438278, 'Mr', '7/25/2021', 'Dowglass');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (60, 'Leland', 'Prinz', 'Research and Development', 813654, 'Rev', '4/15/2020', 'Headon');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (61, 'Blinny', 'Ignaz', 'Sales', 861451, 'Ms', '6/13/2020', 'Boundy');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (62, 'Pia', 'Cristian', 'Marketing', 191736, 'Mrs', '10/22/2020', 'Stove');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (63, 'Annmarie', 'Rees', 'Accounting', 273311, 'Dr', '8/7/2022', 'Shout');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (64, 'Denna', 'Sebastien', 'Sales', 685993, 'Mr', '9/4/2020', 'Dandy');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (65, 'Tawsha', 'Burgess', 'Support', 893551, 'Dr', '12/12/2021', 'Nairne');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (66, 'Sergent', 'Bronson', 'Training', 478245, 'Honorable', '11/27/2020', 'Ellcome');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (67, 'Lammond', 'Bryanty', 'Services', 457109, 'Mr', '5/10/2020', 'De Freyne');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (68, 'Seumas', 'Ewan', 'Services', 55409, 'Dr', '5/10/2022', 'Charlon');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (69, 'Feodor', 'Rory', 'Legal', 693814, 'Rev', '10/6/2020', 'Duckels');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (70, 'Farlay', 'Abby', 'Engineering', 468194, 'Rev', '2/2/2021', 'O''Cannon');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (71, 'Thaddeus', 'Howie', 'Marketing', 427430, 'Ms', '1/24/2021', 'Mowsdale');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (72, 'Jarrett', 'Hazel', 'Research and Development', 730353, 'Rev', '3/15/2022', 'Raubenheimer');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (73, 'Kaleena', 'Lawry', 'Product Management', 226187, 'Ms', '10/12/2022', 'Chomicz');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (74, 'Fran', 'Javier', 'Legal', 930264, 'Ms', '9/24/2021', 'Deville');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (75, 'George', 'Pate', 'Training', 949196, 'Dr', '4/8/2022', 'Yukhnev');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (76, 'Keary', 'Michale', 'Marketing', 773548, 'Dr', '6/14/2021', 'Spurnier');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (77, 'Allie', 'Markus', 'Support', 891682, 'Ms', '9/1/2022', 'Karslake');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (78, 'Saidee', 'Bryon', 'Business Development', 553078, 'Ms', '3/20/2022', 'Weal');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (79, 'Marcelia', 'Winfield', 'Accounting', 821770, 'Dr', '11/4/2021', 'Goaley');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (80, 'Bettina', 'Hugh', 'Human Resources', 295533, 'Dr', '1/31/2022', 'Hubbard');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (81, 'Jasmine', 'Jayme', 'Human Resources', 102336, 'Honorable', '2/8/2021', 'Foyster');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (82, 'Kenon', 'Gordan', 'Support', 544803, 'Dr', '12/7/2021', 'Hawksley');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (83, 'Alidia', 'Rafferty', 'Services', 666837, 'Dr', '9/7/2022', 'Hubbocks');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (84, 'Con', 'Robers', 'Engineering', 759689, 'Ms', '5/28/2021', 'Fugere');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (85, 'Gayler', 'Lane', 'Research and Development', 452335, 'Dr', '6/5/2021', 'Ubank');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (86, 'Sydney', 'Stafford', 'Legal', 815728, 'Dr', '12/27/2019', 'Alekseev');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (87, 'Ermentrude', 'Lowe', 'Support', 777542, 'Dr', '1/13/2021', 'Nisot');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (88, 'Demetra', 'Alanson', 'Business Development', 237545, 'Rev', '10/18/2022', 'Shah');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (89, 'Raddy', 'Clemmy', 'Human Resources', 716127, 'Dr', '7/28/2021', 'Ivancevic');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (90, 'Fancy', 'Che', 'Engineering', 976593, 'Rev', '10/13/2022', 'Bolter');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (91, 'Eli', 'Parsifal', 'Engineering', 169908, 'Rev', '12/28/2019', 'Ragbourne');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (92, 'Haleigh', 'Rance', 'Engineering', 411628, 'Mr', '12/28/2021', 'Duchesne');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (93, 'Jeromy', 'Erroll', 'Human Resources', 321803, 'Dr', '8/9/2022', 'Delaney');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (94, 'Laurent', 'Nowell', 'Training', 378638, 'Ms', '11/26/2021', 'Georger');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (95, 'Durante', 'Ronnie', 'Business Development', 586053, 'Dr', '11/14/2020', 'Ramirez');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (96, 'Graig', 'Neils', 'Services', 255472, 'Rev', '11/8/2022', 'Teaz');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (97, 'Geordie', 'Gerick', 'Research and Development', 151246, 'Rev', '2/16/2020', 'Strapp');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (98, 'Geralda', 'Horace', 'Services', 360880, 'Mr', '3/31/2020', 'Camacho');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (99, 'Roddie', 'Oliver', 'Marketing', 596736, 'Mrs', '11/19/2019', 'Tarquinio');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (100, 'Issiah', 'Neddie', 'Engineering', 667480, 'Honorable', '9/12/2022', 'Rupprecht');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (101, 'Huey', 'Chaim', 'Product Management', 656425, 'Mr', '5/30/2021', 'Ackenhead');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (102, 'Byron', 'Nichole', 'Sales', 698919, 'Ms', '6/3/2021', 'Perrins');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (103, 'Murdock', 'Jamil', 'Support', 543540, 'Honorable', '5/19/2022', 'Faier');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (104, 'Llywellyn', 'Luther', 'Product Management', 416847, 'Rev', '1/1/2020', 'Llewellin');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (105, 'Kaitlyn', 'Kingston', 'Engineering', 687438, 'Mrs', '9/16/2022', 'Hamsher');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (106, 'Paxon', 'Germayne', 'Marketing', 164575, 'Mrs', '12/15/2021', 'Synnott');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (107, 'Melvin', 'Alexandre', 'Legal', 511066, 'Mr', '6/11/2022', 'Sarch');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (108, 'Claribel', 'Damiano', 'Business Development', 3275, 'Mrs', '2/27/2020', 'Poxton');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (109, 'Bunny', 'Nels', 'Research and Development', 650783, 'Dr', '3/23/2022', 'Grzegorecki');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (110, 'Marcia', 'Giavani', 'Product Management', 913741, 'Honorable', '7/21/2022', 'Wrighton');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (111, 'Tresa', 'Yorker', 'Business Development', 800508, 'Rev', '12/18/2019', 'Seely');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (112, 'Delmar', 'Fowler', 'Legal', 548537, 'Rev', '3/3/2022', 'Darrigrand');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (113, 'Barnebas', 'Nicolis', 'Marketing', 357869, 'Dr', '9/2/2020', 'Moulden');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (114, 'Charmian', 'Kalle', 'Support', 831685, 'Mrs', '4/15/2021', 'Fisher');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (115, 'Aubine', 'Renaud', 'Research and Development', 915703, 'Dr', '9/17/2020', 'Lille');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (116, 'Leslie', 'Esteban', 'Training', 961229, 'Mrs', '8/4/2020', 'Gisbye');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (117, 'Myrtice', 'Aylmer', 'Engineering', 568146, 'Ms', '6/2/2021', 'Grindell');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (118, 'Aile', 'Link', 'Support', 132479, 'Mrs', '12/8/2019', 'Hylands');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (119, 'Silvanus', 'Fernando', 'Services', 161293, 'Honorable', '11/15/2020', 'Blinerman');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (120, 'Patrice', 'Mathe', 'Product Management', 60517, 'Honorable', '3/30/2021', 'Abrams');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (121, 'Cordie', 'Devlen', 'Marketing', 64929, 'Dr', '1/5/2022', 'Liveing');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (122, 'Erena', 'Quinn', 'Research and Development', 883118, 'Rev', '9/1/2022', 'Munnis');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (123, 'Barbette', 'Penn', 'Legal', 51417, 'Ms', '3/2/2022', 'Denyer');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (124, 'Hertha', 'Morie', 'Training', 952440, 'Rev', '8/29/2020', 'Hasely');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (125, 'Doralynne', 'Derby', 'Business Development', 220451, 'Honorable', '10/9/2020', 'Cremins');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (126, 'Merry', 'Sloan', 'Engineering', 43721, 'Mr', '10/27/2020', 'Cabral');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (127, 'Marion', 'Witty', 'Marketing', 412937, 'Dr', '3/5/2021', 'Rattry');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (128, 'Marketa', 'Boycey', 'Research and Development', 863259, 'Rev', '6/16/2021', 'Shewring');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (129, 'Austina', 'Allan', 'Product Management', 503633, 'Honorable', '9/19/2022', 'Dominguez');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (130, 'Alexandro', 'Hardy', 'Legal', 354139, 'Mrs', '12/18/2021', 'Mateuszczyk');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (131, 'Kip', 'Domingo', 'Human Resources', 819015, 'Ms', '10/15/2022', 'Steynor');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (132, 'Norrie', 'Hillel', 'Accounting', 53683, 'Mr', '5/28/2021', 'Bernardes');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (133, 'Lark', 'Wilt', 'Legal', 345691, 'Mrs', '3/11/2021', 'Sorsbie');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (134, 'Burk', 'Hubie', 'Business Development', 689747, 'Honorable', '1/16/2022', 'Challener');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (135, 'Amara', 'Kim', 'Training', 780669, 'Honorable', '12/3/2019', 'Wingham');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (136, 'Sergent', 'King', 'Legal', 67270, 'Ms', '4/5/2021', 'Grishanin');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (137, 'Gretchen', 'Vincenty', 'Training', 470761, 'Honorable', '10/1/2022', 'Whiten');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (138, 'Ruperto', 'Paxton', 'Training', 449844, 'Rev', '8/20/2021', 'Purver');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (139, 'Angele', 'Kile', 'Product Management', 50562, 'Honorable', '1/27/2020', 'Hardin');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (140, 'Cristi', 'Lamar', 'Services', 263626, 'Rev', '12/27/2020', 'Kestian');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (141, 'Carolin', 'Bartholomeo', 'Sales', 473976, 'Mr', '12/29/2021', 'Smeed');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (142, 'Lela', 'Simone', 'Sales', 137288, 'Ms', '8/3/2020', 'MacChaell');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (143, 'Roobbie', 'Janek', 'Marketing', 192920, 'Ms', '7/24/2020', 'Harriss');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (144, 'Emanuele', 'Drake', 'Research and Development', 868733, 'Mr', '12/19/2021', 'Pestricke');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (145, 'Otho', 'Shaun', 'Research and Development', 382658, 'Ms', '12/3/2019', 'Lyal');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (146, 'Dani', 'Basil', 'Human Resources', 556645, 'Honorable', '11/20/2020', 'Delong');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (147, 'Kalli', 'Trip', 'Product Management', 582646, 'Honorable', '3/13/2020', 'Rivett');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (148, 'Lanny', 'Derrick', 'Sales', 712195, 'Dr', '6/2/2021', 'McWhin');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (149, 'Uriah', 'Lucius', 'Human Resources', 190824, 'Mr', '5/27/2020', 'Depport');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (150, 'Andras', 'Wilbur', 'Accounting', 676180, 'Ms', '4/21/2020', 'Grewe');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (151, 'Tyne', 'Uriah', 'Human Resources', 361737, 'Honorable', '5/12/2021', 'Coatts');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (152, 'Hunter', 'Sigfrid', 'Marketing', 744226, 'Honorable', '4/26/2022', 'Van Der Walt');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (153, 'Brandice', 'Gilburt', 'Engineering', 95618, 'Rev', '7/24/2021', 'Paddock');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (154, 'Monica', 'Gregg', 'Support', 208897, 'Dr', '2/22/2021', 'Maynard');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (155, 'Loralyn', 'Kristo', 'Sales', 426800, 'Ms', '2/27/2020', 'Munt');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (156, 'Lilyan', 'Danya', 'Product Management', 989945, 'Dr', '7/28/2022', 'Rowe');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (157, 'Piggy', 'Reuben', 'Engineering', 642315, 'Ms', '3/2/2020', 'Roxby');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (158, 'Auroora', 'Monti', 'Business Development', 437937, 'Honorable', '8/27/2021', 'Kirckman');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (159, 'Hattie', 'Hallsy', 'Product Management', 891493, 'Dr', '5/19/2021', 'Kilfeather');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (160, 'Pete', 'Leslie', 'Accounting', 560286, 'Dr', '9/25/2020', 'Lavigne');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (161, 'Kellen', 'Armin', 'Marketing', 713328, 'Dr', '4/7/2022', 'Azema');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (162, 'Vidovic', 'Moss', 'Support', 961316, 'Ms', '5/13/2020', 'Battson');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (163, 'Penelopa', 'Kiel', 'Marketing', 473002, 'Rev', '11/22/2019', 'Shafe');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (164, 'Malva', 'Hanson', 'Support', 796143, 'Ms', '3/16/2022', 'Eastam');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (165, 'Arlin', 'Lalo', 'Services', 737502, 'Rev', '7/16/2021', 'Geeritz');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (166, 'Dode', 'Donaugh', 'Engineering', 654743, 'Ms', '12/8/2021', 'Joinsey');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (167, 'Ailbert', 'Hermann', 'Services', 819203, 'Honorable', '3/12/2022', 'Ulster');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (168, 'Marget', 'Arie', 'Sales', 539218, 'Rev', '9/2/2022', 'Jessen');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (169, 'Nessie', 'Cecilio', 'Engineering', 217932, 'Ms', '1/2/2021', 'Maillard');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (170, 'Rafferty', 'Darcy', 'Training', 916770, 'Rev', '10/26/2021', 'Notman');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (171, 'Sutherland', 'Noam', 'Legal', 343958, 'Dr', '12/17/2020', 'Doulden');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (172, 'Yolanda', 'Mickie', 'Training', 388313, 'Ms', '4/30/2022', 'Kindred');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (173, 'Ninette', 'Isacco', 'Marketing', 685075, 'Ms', '6/28/2022', 'Louw');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (174, 'Bebe', 'Alejandro', 'Legal', 85107, 'Ms', '7/24/2022', 'Colthard');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (175, 'Cheslie', 'Lance', 'Marketing', 881305, 'Honorable', '3/10/2022', 'Grinston');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (176, 'Sylvester', 'Ferguson', 'Support', 785455, 'Rev', '10/17/2022', 'Baudet');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (177, 'Georgie', 'Zaccaria', 'Product Management', 686676, 'Mrs', '12/26/2020', 'Matuszyk');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (178, 'Franky', 'Marc', 'Engineering', 245282, 'Ms', '2/20/2020', 'Ply');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (179, 'Boyd', 'Paquito', 'Sales', 636161, 'Rev', '8/9/2021', 'Trayford');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (180, 'Christophorus', 'Aron', 'Legal', 63075, 'Mrs', '4/19/2022', 'Beric');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (181, 'Karalee', 'Felizio', 'Engineering', 971124, 'Ms', '4/28/2022', 'Wegenen');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (182, 'Vivie', 'Josias', 'Accounting', 57086, 'Ms', '7/26/2022', 'MacRury');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (183, 'Lilian', 'Kerby', 'Research and Development', 1432, 'Ms', '9/4/2022', 'Blackston');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (184, 'Mahalia', 'Silvain', 'Support', 88213, 'Mrs', '4/8/2022', 'Ortner');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (185, 'Earle', 'Jessey', 'Product Management', 400709, 'Mrs', '9/27/2020', 'Pietruszewicz');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (186, 'Jemmie', 'Vasily', 'Accounting', 147310, 'Honorable', '10/24/2021', 'Minillo');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (187, 'Sephira', 'Tan', 'Legal', 376277, 'Mrs', '4/27/2020', 'Gorelli');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (188, 'Hollis', 'Tomkin', 'Services', 376532, 'Dr', '11/27/2020', 'Atterbury');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (189, 'Salome', 'Bogart', 'Product Management', 500351, 'Honorable', '6/21/2021', 'Fardy');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (190, 'Cecilla', 'Sigismund', 'Marketing', 63583, 'Honorable', '10/21/2020', 'Piggrem');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (191, 'Arte', 'Balduin', 'Legal', 138729, 'Honorable', '11/28/2020', 'Lovewell');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (192, 'Riannon', 'Grady', 'Training', 114722, 'Mrs', '8/1/2022', 'Silbermann');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (193, 'Hayley', 'Sinclare', 'Legal', 328137, 'Mrs', '10/25/2022', 'Divell');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (194, 'Andris', 'Jules', 'Training', 452479, 'Mrs', '4/1/2020', 'Piper');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (195, 'Cecily', 'Reider', 'Legal', 170952, 'Dr', '9/3/2020', 'Catcherside');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (196, 'Gae', 'Eadmund', 'Engineering', 907530, 'Dr', '9/1/2021', 'Van der Baaren');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (197, 'Porty', 'Shawn', 'Services', 199498, 'Mrs', '9/28/2021', 'Wrightam');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (198, 'Frayda', 'Timmy', 'Marketing', 652777, 'Dr', '6/23/2022', 'Tallquist');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (199, 'Bruno', 'Whitney', 'Accounting', 370544, 'Mrs', '4/11/2022', 'Quick');
insert into teachers (id, first_name, futher_name, department, salary, qualification_level, contract_termination, last_name) values (200, 'Spencer', 'Bennett', 'Business Development', 853572, 'Dr', '12/9/2021', 'Roser');
